"""initial schema: sources + events

Revision ID: 0001
Revises:
Create Date: 2026-07-25

Hand-written (not autogenerated) so the reviewer can read exactly what hits the
database: the event_status enum, both tables, the idempotency unique constraint,
and the indexes the worker relies on.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Create the enum explicitly so we control it in both directions. create_type is
# False so that create_table below does NOT also try to emit CREATE TYPE (which
# would fail as a duplicate) — the explicit create()/drop() calls own the type.
event_status = postgresql.ENUM(
    "pending",
    "delivering",
    "delivered",
    "failed",
    "dead",
    name="event_status",
    create_type=False,
)


def upgrade() -> None:
    event_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "sources",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("signing_secret", sa.Text(), nullable=False),
        sa.Column("downstream_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_sources_name"),
    )

    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_event_id", sa.Text(), nullable=False),
        sa.Column("resource_key", sa.Text(), nullable=False),
        sa.Column("status_ordinal", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            event_status,
            nullable=False,
            server_default="pending",
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # Idempotency: the database guarantees at most one row per
        # (source, provider_event_id). See app/models.py for the why.
        sa.UniqueConstraint("source_id", "provider_event_id", name="uq_events_source_provider"),
    )

    # Worker "find due work" query filters on status and orders by next_attempt_at.
    op.create_index(
        "ix_events_status_next_attempt_at",
        "events",
        ["status", "next_attempt_at"],
    )
    # The monotonic guard looks up the highest delivered ordinal per resource_key.
    op.create_index(
        "ix_events_resource_key_ordinal",
        "events",
        ["resource_key", "status_ordinal"],
    )
    op.create_index("ix_events_source_id", "events", ["source_id"])


def downgrade() -> None:
    op.drop_index("ix_events_source_id", table_name="events")
    op.drop_index("ix_events_resource_key_ordinal", table_name="events")
    op.drop_index("ix_events_status_next_attempt_at", table_name="events")
    op.drop_table("events")
    op.drop_table("sources")
    event_status.drop(op.get_bind(), checkfirst=True)
